from fpdf import FPDF
import datetime
import io

class MetaMLReporter:
    def __init__(self):
        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)
        self.pdf.add_page()
        
    def generate_project_report(self, result: dict):
        """Build a professional PDF audit report for an ML project."""
        prob = result["success_probability"]
        features = result["features"]
        metadata = result["metadata"]
        
        # --- HEADER ---
        self.pdf.set_font("Helvetica", "B", 24)
        self.pdf.set_text_color(15, 23, 42) # Slate 900
        self.pdf.cell(0, 20, "META ML PROJECT AUDIT", 0, 1, "C")
        self.pdf.set_font("Helvetica", "", 10)
        self.pdf.set_text_color(100)
        self.pdf.cell(0, 10, f"Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, "C")
        self.pdf.ln(10)
        
        # --- SUMMARY SECTION ---
        self.pdf.set_fill_color(248, 250, 252) # Slate 50
        self.pdf.set_font("Helvetica", "B", 14)
        self.pdf.set_text_color(71, 85, 105) # Slate 600
        self.pdf.cell(0, 12, " PROJECT SUMMARY", 0, 1, "L", fill=True)
        self.pdf.ln(2)
        
        self.pdf.set_font("Helvetica", "B", 11)
        self.pdf.set_text_color(15, 23, 42)
        self.pdf.cell(40, 8, "Repository URL:")
        self.pdf.set_font("Helvetica", "", 11)
        self.pdf.cell(0, 8, result["features"].get("github_url", "N/A"), 0, 1)
        
        self.pdf.set_font("Helvetica", "B", 11)
        self.pdf.cell(40, 8, "Paper Title:")
        self.pdf.set_font("Helvetica", "", 11)
        self.pdf.cell(0, 8, metadata.get("scholar_data", {}).get("paper_title", "N/A"), 0, 1)
        self.pdf.ln(5)
        
        # --- VIABILITY SCORE ---
        self.pdf.set_font("Helvetica", "B", 14)
        self.pdf.set_text_color(71, 85, 105)
        self.pdf.cell(0, 12, " SUCCESS VIABILITY SCORE", 0, 1, "L", fill=True)
        self.pdf.ln(5)
        
        self.pdf.set_font("Helvetica", "B", 48)
        # Color based on score
        if prob > 0.7: self.pdf.set_text_color(22, 163, 74) # Green 600
        elif prob > 0.4: self.pdf.set_text_color(202, 138, 4) # Yellow 600
        else: self.pdf.set_text_color(220, 38, 38) # Red 600
        
        self.pdf.cell(0, 30, f"{prob:.1%}", 0, 1, "C")
        
        self.pdf.set_font("Helvetica", "B", 12)
        risk = "LOW RISK" if prob > 0.7 else "MEDIUM RISK" if prob > 0.4 else "HIGH RISK"
        self.pdf.cell(0, 10, f"Verdict: {risk}", 0, 1, "C")
        self.pdf.ln(10)
        
        self.pdf.ln(10)
        
        # --- RISK DNA & CONSENSUS ---
        self.pdf.set_font("Helvetica", "B", 14)
        self.pdf.set_text_color(71, 85, 105)
        self.pdf.cell(0, 12, " EXECUTIVE RISK ANALYSIS", 0, 1, "L", fill=True)
        self.pdf.ln(5)
        
        self.pdf.set_font("Helvetica", "B", 11)
        self.pdf.set_text_color(15, 23, 42)
        risk_type = result.get("risk_taxonomy", "Stable")
        self.pdf.cell(0, 8, f"Primary Risk Factor: {risk_type.upper()}", 0, 1)
        
        self.pdf.ln(5)
        self.pdf.set_font("Helvetica", "B", 14)
        self.pdf.cell(0, 10, "AGENT CONSENSUS", 0, 1)
        self.pdf.set_font("Helvetica", "", 10)
        consensus = result.get("agent_consensus", {})
        for agent, score in consensus.items():
            self.pdf.cell(50, 8, f"{agent.capitalize()} Agent Vote:")
            self.pdf.set_font("Helvetica", "B", 10)
            self.pdf.cell(0, 8, f"{int(score * 100)}%", 0, 1)
            self.pdf.set_font("Helvetica", "", 10)

        self.pdf.ln(10)
        
        # --- DISCLAIMER ---
        self.pdf.set_font("Helvetica", "I", 8)
        self.pdf.set_text_color(150)
        self.pdf.multi_cell(0, 5, "This report is generated by the META ML AI Engine. It is based on point-in-time signals from the open-source and research ecosystem and should not be taken as financial or investment advice.")

    def get_pdf_bytes(self):
        """Return the PDF content as bytes."""
        return bytes(self.pdf.output())
